# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.6.3"

# Faz a instalação com Sudo, para ter privilégio de Super Usuário.
sudo: required

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask

# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python test.py

# Defini que o processo de Deploy será na Plataforma Heroku. É necessário informar o nome da APP criada no Heroku
deploy:
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  app: app4linux
